# When accessing this in the code you'll work with it as a dict.
# ENV variables will be replaced with their values. This is done with the envyaml package that is in the code template `load_config`.
# By convention all variables for the project should have the MICROBESEQ_NBDEV_EXAMPLE_* prefix.
# e.g
# name: ${MICROBESEQ_NBDEV_EXAMPLE_NAME}
example:
    input:
        name: ${MICROBESEQ_NBDEV_EXAMPLE_USER_INPUT_NAME}
        alternative_name: Lee
